### ISSUE TITLE
cdt-gdb-vscode's debug adapter path looks incorrect

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt-cloud/cdt-gdb-vscode#104]
The [v0.0.104 version](https://open-vsx.org/extension/eclipse-cdt/cdt-gdb-vscode) of the extension recently published doesn't work, my guess on quick inspection is this line is wrong:

https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/blob/be6966dd625b0b002366d50f9c0683ef3b826697/package.json#L63

@colin-grant-work this seems to be a regression due to #96

**Comment by jonahgraham** [comment]
I think https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/commit/ccd5af4451397f67889e4e4441a2a1b6a236f592 which was supposed to have been in PR #96 didn't make it back to the PR following https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/commit/ccd5af4451397f67889e4e4441a2a1b6a236f592#r126102818?

**Comment by colin-grant-work** [comment]
Looks like you're right. Apologies for the double mixup.

**Comment by jonahgraham** [comment]
No worries - I think I tested it just by running in dev environment so didn't see the problem. Before I publish the next version I will try creating a full vsix and install in a clean location.

**Comment by jonahgraham** [comment]
I have tagged the version with the fix as v0.0.105 that should be published overnight. I have asked (https://github.com/EclipseFdn/open-vsx.org/issues/2171) how this happens as I am not confident that I have reproduced how this gets published.
