### ISSUE TITLE
Starting a debug session triggers the error "Don't know how to run. Try "help target"."

### ISSUE THREAD

**Issue by omarArm** [eclipse-cdt-cloud/cdt-gdb-vscode#128]
Hi,

I am trying to use the extension to run the command arm-none-eabi-gdb <my_program.elf>. However, I am receiving the error 

```
Don't know how to run. Try "help target".
```

Here is my launch.json configuration,

```
{
            "type": "gdb",
            "request": "launch",
            "name": "Debug with eclipe",
            "program": "${workspaceFolder}/armgcc/debug/led_blinky_cm0.elf",
            "cwd": "${workspaceFolder}",
            "verbose": true,
            "openGdbConsole": true,
            "gdb": "arm-none-eabi-gdb"        
}
```

It is the first time I use the extension, so please go easy on me and assume that I know nothing 

Environment:

Machine: macOS, Sequoia 15.1, M2 chip
VScode version: 1.96.0
Extension version: 1.0.1

**Comment by omarArm** [comment]
Thanks a lot for your quick reply. I am now trying two different approaches
1. using the `request: "attach"`, because obviously that is the easier route that would make things work faster.
2. using the `request: "launch"`, because I want to start my debugging session from a single gate. As in just with the click of a button everything works, without the need to start a gdbserver on another terminal


Now regarding option 1, I have the following launch.json configuration and it looks like the gdb session is starting and connecting to the server, but I don't know how to use it. I tried sending some gdb commands via the Debug Console, but I always received the following reply
```
b main
From client: evaluate({"expression":"b main","context":"repl"})
To client: {"seq":0,"type":"response","request_seq":6,"command":"evaluate","success":false,"body":{"result":"Error: could not evaluate expression","variablesReference":0,"error":{"id":1,"format":"Evaluation of expression without frameId is not supported.","showUser":true}},"message":"Evaluation of expression without frameId is not supported."}
Evaluation of expression without frameId is not supported.
```
Also nothing appears on my source code, no break points set, no stepping, nothing.

Here is my launch.json for the attach request
```
   {
            "type": "gdbtarget",
            "request": "attach",
            "name": "Debug with eclipe attaching",
            "program": "${workspaceFolder}/armgcc/debug/led_blinky_cm0.elf",
            "cwd": "${workspaceFolder}",
            "verbose": true,
            "gdb": "arm-none-eabi-gdb",
            "openGdbConsole": true,
            "target": {
                "host": "localhost",
                "port": "3333"
            }
  }
```

Now regarding option 2, I would like to run the gdbserver using pyocd, so I added `server: "pyocd gdbserver"` to my configuration. However, I am facing another error that is
```
gdbserver has hit error Error: spawn pyocd gdbserver ENOENT
```

Please find here my launch.json for the launch request
```
       {
            "type": "gdbtarget",
            "request": "launch",
            "name": "Debug with eclipe launching",
            "program": "${workspaceFolder}/armgcc/debug/led_blinky_cm0.elf",
            "cwd": "${workspaceFolder}",
            "verbose": true,
            "gdb": "/Users/omaelk01/.vcpkg/artifacts/2139c4c6/compilers.arm.arm.none.eabi.gcc/13.3.1/bin/arm-none-eabi-gdb",
            "target": {
                "server": "pyocd gdbserver",
                "type": "local",
                "port": "3333",
                "serverParameters": []
            }

}
```

Sorry to be bombarding you with all of that. Any help would be appreciated

**Comment by jonahgraham** [comment]
> Now regarding option 2, I would like to run the gdbserver using pyocd, so I added `server: "pyocd gdbserver"` to my configuration. However, I am facing another error that is

The `server` needs to be a command, so just `pyocd` in this case and then any command line parameters passed in `serverParameters`, e.g.  `"serverParameters": ["gdbserver"]`

If you are interested in under the hood, this is because of how `server` and `serverParameters` are passed to [`spawn`](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options): ([source link](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/590fea58cfb2ee4984d766cd1b2140738d3ff110/src/desktop/processManagers/GDBServerFileSystemProcessManager.ts#L61-L64))

**Comment by omarArm** [comment]
It is working now, thank you!
