### ISSUE TITLE
UI Test Strategy

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt-cloud/cdt-gdb-vscode#24]
Now that we have an incoming Memory Browser that uses vscode's webview API and React, how do we test such a thing?

This would include unit testing the components, testing of the UI while mocking out the back end server (i.e. the extension), and end to end testing in vscode (if that's even possible?)

**Comment by jonahgraham** [comment]
I expect the memory browser to be removed when https://github.com/eclipse-cdt-cloud/vscode-memory-inspector is fully working, so no point investing further in testing infra on this in cdt-gdb-vscode, that work should happen on vscode-memory-inspector
