### ISSUE TITLE
Can not wait for user input with getchar() at least

### ISSUE THREAD

**Issue by jgueytat** [eclipse-cdt-cloud/cdt-gdb-vscode#43]
For now I was only able to get the user input properly with the Microsoft C++ extension.

I'm expected to see : **Press enter to continue...** when the program is started.

**No possible interation :**
![Started](https://user-images.githubusercontent.com/1152718/112302238-2431e000-8c9b-11eb-9f7a-098ae9ce414b.png)
![Stopped](https://user-images.githubusercontent.com/1152718/112301215-fbf5b180-8c99-11eb-9cb4-5d75a44ef7ec.png)

**The command line is ok :**
![The command line is ok.](https://user-images.githubusercontent.com/1152718/112301228-fef0a200-8c99-11eb-99c0-54f5612c0417.png)

**ps:** I can hit the breakpoints normally.

**Comment by jonahgraham** [comment]
This issue is with the adapter itself and is tracked by https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/161 which is to have a "proper" inferior process I/O
