### ISSUE TITLE
How to spawn gdb with superuser permission (sudo)?

### ISSUE THREAD

**Issue by yakamoz423** [eclipse-cdt-cloud/cdt-gdb-vscode#61]
I installed cdt-gdb-vscode in VS Code on Windows, and opened a folder in Remote WSL mode. Then start debugging, gdb says `ptrace: Operation not permitted`. The same warning is shown when I use bash instead. But in bash, debugging session works via `sudo gdb attach xxx`command. So how to launch "sudo gdb" to start debugging? Thanks for replying!

launch.json configurations is:
```
        {
            "type": "gdb",
            "request": "attach",
            "name": "linux",
            "gdb": "gdb",
            "processId": "${command:askProcessId}",
            "program": "/usr/bin/vi",
            "verbose": "true",
        }
```

**Comment by paul-marechal** [comment]
I don't know if it would work but I'd make a `sudo_gdb.sh` script like:

```sh
#!/bin/bash
sudo gdb $@
```

And then point the configuration to spawn this script instead of gdb directly?

**Comment by yakamoz423** [comment]
Thank you, it works. I used `expect` script instead.
```
#!/usr/bin/expect

spawn sudo gdb $argv
expect "password for <username>: "
send "<password>\n"
interact
```

**Comment by jonahgraham** [comment]
The workaround of using the script is ok, but the other solution may be to enable ptrace, see for example this SO answer https://stackoverflow.com/a/32274645/2796832
