### ISSUE TITLE
Add Memory webview

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt-cloud/cdt-gdb-vscode#8]
Using the React component provided by the cdt-gdb-adapter for memory, create a webview panel to show memory.

**Comment by dschaefer** [comment]
So my current thinking is to do something similar to PlatformIO. (Funny story about that, even though it's on npm, their debug extension code is actually close sourced. Which is fine, just weird.)

Add a view for "Memory" in the Debug activity. Each entry in the view is a memory range. Add commands and menus to add/remove them. When you click on a range, we open up a webview panel to render the memory contents.

The list of active ranges should be based on the current debug session. Just need to figure out how to use the API to manage that.

**Comment by dschaefer** [comment]
OK, this is up next for me.

**Comment by dschaefer** [comment]
29 days later, still thinking about it. Soon :)

Anyway, the idea is to create a webview for the Memory Browser. It would look and function like CDT's Memory Browser.

We would build it using React, since that's been most popular for a while now. Still need to see what or if which UI library we use, though, I've been using material-ui lately for stuff. Also seems quite popular.

We could also create a viewlet for the Debug view to keep a history of locations to make it easier to pop them up from session to session. Though we should also keep a history in the address field.

Any other thoughts?

**Comment by simark** [comment]
Here is the current implementation in Theia:

**Comment by dschaefer** [comment]
OK, I'll take that as permission :). Certainly give me a leg up. Thanks!

I'll assume you guys have approval to use React then. I'll need to submit a similar CQ to use it here. Hopefully I can find it and save some of the effort.

I will be very curious at how compatible Theia's vscode extension compatibility is as we wrap this up in a webview and message back to the main process to call into the debugger APIs.

**Comment by simark** [comment]
> I will be very curious at how compatible Theia's vscode extension compatibility is as we wrap this up in a webview and message back to the main process to call into the debugger APIs.

It will likely be very broken in Theia, but we'll need to work to make it run :).

**Comment by GitMensch** [comment]
This issue is a bit old - but maybe it is possible to now change that (possibly in Theia and here) to use the same approach as Visual Studio Code does - by using the hexedit extension and its views?

**Comment by jonahgraham** [comment]
Theia has a memory inspector now that is more fully featured. Not sure how exactly it will be enabled where, but have a look at https://youtu.be/cDPAl9nzAhg?t=930 (the memory inspector starts at 15:30). The code is currently here: https://github.com/eclipse-theia/theia-cpp-extensions/tree/d537453bdc6c08fea728c54c2f9c43d7428ebb19/packages/cpp-debug#memory-widget

**Comment by jonahgraham** [comment]
https://github.com/eclipse-cdt-cloud/vscode-memory-inspector is a real incoming thing now, so nothing to do here anymore.
