### ISSUE TITLE
cdt-gdb-vscode 0.0.101 not ending up on Open VSX

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt-cloud/cdt-gdb-vscode#95]
I pushed 0.0.101 to cdt-gdb-vscode a few days ago but it hasn't shown up on open vsx yet. I am not sure how to give this a kick or who to report this to.

@sdirix, @thegecko, @planger do any of you know how/who to ask to make latest cdt-gdb-vscode show up?

**Comment by thegecko** [comment]
There have been some issues recently, e.g. 

https://github.com/eclipse/openvsx/issues/779

Recommend opening an issue there.
